# Generated by Django 5.2.8 on 2025-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0002_user_checking_time_user_current_feel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_done',
            field=models.IntegerField(default=0),
        ),
    ]
