# Generated by Django 5.2.8 on 2025-11-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0003_alter_user_profile_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
