# Generated by Django 5.2.8 on 2025-11-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='checking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
