# Generated by Django 5.2.8 on 2025-11-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0005_alter_user_checking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_stack_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
