# Generated by Django 5.2.8 on 2025-11-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0006_user_last_stack_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checking_time',
        ),
    ]
