# Generated by Django 5.2.8 on 2025-11-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0007_remove_user_checking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checking_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
