# Generated by Django 5.2.8 on 2025-11-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0008_user_checking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avarage',
            field=models.IntegerField(default=0),
        ),
    ]
