# Generated by Django 5.2.8 on 2025-11-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.IntegerField(choices=[(10, 'Excellent 😄'), (9, 'Very Good 😊'), (8, 'Good 🙂'), (7, 'Okay 😌'), (6, 'Neutral 😐'), (5, 'Slightly Off 🙃'), (4, 'Low 😔'), (3, 'Stressed 😣'), (2, 'Sad 😢'), (1, 'Awful 😫')])),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
