# Generated by Django 5.2.8 on 2025-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychecking',
            name='feeling',
            field=models.CharField(choices=[('Excellent 😄', 'Excellent 😄'), ('Very Good 😊', 'Very Good 😊'), ('Good 🙂', 'Good 🙂'), ('Okay 😌', 'Okay 😌'), ('Neutral 😐', 'Neutral 😐'), ('Slightly Off 🙃', 'Slightly Off 🙃'), ('Low 😔', 'Low 😔'), ('Stressed 😣', 'Stressed 😣'), ('Sad 😢', 'Sad 😢'), ('Awful 😫', 'Awful 😫')], max_length=50),
        ),
    ]
