# Generated by Django 5.2.8 on 2025-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checking', '0002_alter_dailychecking_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychecking',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
