# Generated by Django 5.2.8 on 2025-11-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checking', '0003_dailychecking_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychecking',
            name='feeling',
            field=models.CharField(choices=[('Awful 😫', 'Awful 😫'), ('Sad 😢', 'Sad 😢'), ('Slightly Off 😕', 'Slightly Off 😕'), ('Stressed 😣', 'Stressed 😣'), ('Anxious 😰', 'Anxious 😰'), ('Tired 😴', 'Tired 😴'), ('Neutral 😐', 'Neutral 😐'), ('Calm 😌', 'Calm 😌'), ('Happy 😄', 'Happy 😄'), ('Excited 🤩', 'Excited 🤩')], max_length=50),
        ),
    ]
